#!/bin/bash

set -e

SNAPSHOT_PATH=/home/pi/snapshots
mkdir -p "$SNAPSHOT_PATH"
CURRENT_SNAPSHOT_PATH="$SNAPSHOT_PATH/last.jpg"
echo "taking snapshot $CURRENT_SNAPSHOT_PATH"

ffmpeg -y -i rtsp://:8554/ -vframes 1 "$CURRENT_SNAPSHOT_PATH"

echo "snapshot saved $CURRENT_SNAPSHOT_PATH"