#!/bin/bash

set -e

mkdir -p /home/pi/snapshots
DATE=$(date +"%Y-%m-%d_%H%M")
SNAPSHOT_NAME="$DATE.jpg"
SNAPSHOT_PATH="/home/pi/snapshots/$SNAPSHOT_NAME"
CURRENT_SNAPSHOT_PATH="/home/pi/snapshots/current.jpg"
echo "taking snapshot $SNAPSHOT_PATH"

raspistill \
  -o "$SNAPSHOT_PATH"
  # --width 2048 \
  # --height 1536 \
  # --width 1024 \
  # --height 768 \

echo "snapshot saved $SNAPSHOT_PATH"
cp "$SNAPSHOT_PATH" "$CURRENT_SNAPSHOT_PATH"
echo "saving current.jpg $SNAPSHOT_PATH"