#!/bin/bash

source secrets

aws lambda invoke --region $REGION --function-name GardenTimelapse --payload "{\"bucket\":\"$BUCKET\", \"amount\": 48, \"fps\": 6}" out --log-type Tail --query 'LogResult' --output text | base64 --decode

cat out
